name: Publish Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    uses: ndkhanh-axonivy/github-workflows/.github/workflows/publish-release.yml@v4
    # The release should be published automatically.
    # Uncommalse' if you want to prevent the release from being published immediately.
    # with:
    #   publish_release: false