name: Publish Release

on:
  push:
    branch:
      - master
    tags:
      - "v*.*.*"

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    uses: ndkhanh-axonivy/github-workflows/.github/workflows/publish-release.yml@v4
    with:
      publish_release: false