name: Release Drafter

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  build:
    uses: ndkhanh-axonivy/github-workflows/.github/workflows/release-drafter.yml
