name: Release Drafter

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: false
      prerelease:
        description: 'Is this a prerelease?'
        required: false
        default: 'false'
        type: boolean

jobs:
  build:
    uses: ndkhanh-axonivy/github-workflows/.github/workflows/release-drafter.yml@master
    with:
      version: ${{ github.event.inputs.version }}
      prerelease: ${{ github.event.inputs.prerelease }}